# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables: 
- group: DayTrackingVar
  

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '>=3.0'
    githubToken: '$(Token)'
    addToPath: true
    architecture: 'x64'
  displayName: 'Use Python >=3.0'
    
  
- task: CmdLine@2
  inputs:
    script: |
      echo Working Directory
      echo  '$(System.DefaultWorkingDirectory)'
      dir
      cat data.csv
      pip install -r requirements.txt 
      echo "Running Python script"  
      python dataGenerator.py  
     


- script: | 
    git config --global user.email "swa.deep@outlook.com" 
    git config --global user.name "Swadeep888"
    git config --global --add url."git@github.com:Swadeep888/data-generator".insteadOf "https://github.com/Swadeep888/data-generator" 
    git clone https://github.com/Swadeep888/data-generator.git
    git add data.csv 
    git commit -m "Update CSV file" 
    git push origin HEAD:Swadeep888/data-generator
  displayName: 'Commit and push changes' 
  env:
    githubToken: '$(Token)'
    

     
 