# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables: 
   variable_group: DayTrackingVar
  

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '>=3.0'
    githubToken: '${Token}'
    addToPath: true
    architecture: 'x64'
  displayName: 'Use Python >=3.0'
    
  
- task: CmdLine@2
  inputs:
    script: |
      echo Working Directory
      
      echo  '$(System.DefaultWorkingDirectory)'

      dir
      
- script: |  
    pip install -r requirements.txt 
    echo "Running Python script"  
    python dataGenerator.py  
  displayName: 'Run Python Script' 
     
    
- task: GitHubComment@0
  inputs:
    gitHubConnection: 'Swadeep888'
    repositoryName: '$(Build.Repository.Name)'
    comment: 'New line added'
    